[package]
name = "chicago-gtfs-rt"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gtfs-rt = "0.4.0"
reqwest = "0.11.22"
tokio = { features = ["full"], version = "1.35.0" }
